include(ExternalProject)

set(HTS_ENGINE_VERSION "1.10")
set(HTS_ENGINE_DIR "${CMAKE_CURRENT_BINARY_DIR}/he")
set(HTS_ENGINE_ARCHIVE_NAME "hts_engine_API-${HTS_ENGINE_VERSION}.tar.gz")
set(HTS_ENGINE_ARCHIVE_SHA256 "e2132be5860d8fb4a460be766454cfd7c3e21cf67b509c48e1804feab14968f7")
set(HTS_ENGINE_ARCHIVE_PATH "${CMAKE_SOURCE_DIR}/thirdparty/distfiles/${HTS_ENGINE_ARCHIVE_NAME}")
set(HTS_ENGINE_REMOTE_URLS
  "https://deb.debian.org/debian/pool/main/h/htsengine/htsengine_${HTS_ENGINE_VERSION}.orig.tar.gz"
  "https://downloads.sourceforge.net/project/hts-engine/hts_engine%20API/hts_engine_API-${HTS_ENGINE_VERSION}/hts_engine_API-${HTS_ENGINE_VERSION}.tar.gz"
)

if(EXISTS "${HTS_ENGINE_ARCHIVE_PATH}")
  set(HTS_ENGINE_URL_ARGS URL "${HTS_ENGINE_ARCHIVE_PATH}")
else()
  set(HTS_ENGINE_URL_ARGS URL ${HTS_ENGINE_REMOTE_URLS})
endif()

if(WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Android" OR CMAKE_SYSTEM_NAME STREQUAL "iOS" OR
   CMAKE_SYSTEM_NAME STREQUAL "Emscripten" OR
   (CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64" AND CMAKE_SYSTEM_NAME STREQUAL "Linux"))
  # CMake build (Windows, Android, iOS, Linux ARM64)
  ExternalProject_Add(
    hts_engine_external
    PREFIX "${CMAKE_CURRENT_BINARY_DIR}/h"
    ${HTS_ENGINE_URL_ARGS}
    URL_HASH SHA256=${HTS_ENGINE_ARCHIVE_SHA256}
    CMAKE_ARGS
      -DCMAKE_INSTALL_PREFIX:PATH=${HTS_ENGINE_DIR}
      -DCMAKE_BUILD_TYPE:STRING=${EXTERNAL_BUILD_TYPE}
      -DBUILD_SHARED_LIBS:BOOL=OFF
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
      -DHTS_EMBEDDED:BOOL=ON
      -DBUILD_HTS_ENGINE_EXECUTABLE:BOOL=OFF
      ${EXTERNAL_CMAKE_ARGS}
    BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --config ${EXTERNAL_BUILD_TYPE}
    INSTALL_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --target install --config ${EXTERNAL_BUILD_TYPE}
    PATCH_COMMAND ${CMAKE_COMMAND}
      -DHTS_ENGINE_SOURCE_DIR=<SOURCE_DIR>
      -DPIPER_PLUS_SOURCE_DIR=${CMAKE_CURRENT_SOURCE_DIR}
      -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/PatchHTSEngine.cmake
    BUILD_BYPRODUCTS
      ${HTS_ENGINE_DIR}/lib/HTSEngine.lib
      ${HTS_ENGINE_DIR}/lib/libHTSEngine.a
  )
else()
  # Autotools build (macOS, Linux x86_64)
  ExternalProject_Add(
    hts_engine_external
    PREFIX "${CMAKE_CURRENT_BINARY_DIR}/h"
    ${HTS_ENGINE_URL_ARGS}
    URL_HASH SHA256=${HTS_ENGINE_ARCHIVE_SHA256}
    CONFIGURE_COMMAND <SOURCE_DIR>/configure --prefix=${HTS_ENGINE_DIR} "CFLAGS=-O2 -fPIC"
    BUILD_COMMAND make
    INSTALL_COMMAND make install
    BUILD_IN_SOURCE 1
    BUILD_BYPRODUCTS ${HTS_ENGINE_DIR}/lib/libHTSEngine.a
  )
endif()
