include(ExternalProject)

set(OPENJTALK_VERSION "1.11")
set(OPENJTALK_DIR "${CMAKE_CURRENT_BINARY_DIR}/oj")
set(OPENJTALK_ARCHIVE_NAME "open_jtalk-${OPENJTALK_VERSION}.tar.gz")
set(OPENJTALK_ARCHIVE_SHA256 "20fdc6aeb6c757866034abc175820573db43e4284707c866fcd02c8ec18de71f")
set(OPENJTALK_ARCHIVE_PATH "${CMAKE_SOURCE_DIR}/thirdparty/distfiles/${OPENJTALK_ARCHIVE_NAME}")
set(OPENJTALK_REMOTE_URLS
  "https://deb.debian.org/debian/pool/main/o/open-jtalk/open-jtalk_${OPENJTALK_VERSION}.orig.tar.gz"
  "https://downloads.sourceforge.net/project/open-jtalk/Open%20JTalk/open_jtalk-${OPENJTALK_VERSION}/open_jtalk-${OPENJTALK_VERSION}.tar.gz"
)

if(EXISTS "${OPENJTALK_ARCHIVE_PATH}")
  set(OPENJTALK_URL_ARGS URL "${OPENJTALK_ARCHIVE_PATH}")
else()
  set(OPENJTALK_URL_ARGS URL ${OPENJTALK_REMOTE_URLS})
endif()

set(OPENJTALK_CMAKE_ARGS
  -DCMAKE_INSTALL_PREFIX:PATH=${OPENJTALK_DIR}
  -DCMAKE_BUILD_TYPE:STRING=${EXTERNAL_BUILD_TYPE}
  -DBUILD_SHARED_LIBS:BOOL=OFF
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
  -DCMAKE_CXX_STANDARD:STRING=14
  -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
  -DHTS_ENGINE_INCLUDE_DIR:PATH=${HTS_ENGINE_DIR}/include
  -DPIPER_PLUS_USE_PTHREADS:BOOL=${PIPER_PLUS_USE_PTHREADS}
  ${EXTERNAL_CMAKE_ARGS}
)

if(WIN32)
  # CMAKE_MSVC_RUNTIME_LIBRARY is already passed via EXTERNAL_CMAKE_ARGS
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/HTSEngine.lib
  )
else()
  list(APPEND OPENJTALK_CMAKE_ARGS
    -DHTS_ENGINE_LIB:FILEPATH=${HTS_ENGINE_DIR}/lib/libHTSEngine.a
  )
endif()

ExternalProject_Add(
  openjtalk_external
  PREFIX "${CMAKE_CURRENT_BINARY_DIR}/o"
  ${OPENJTALK_URL_ARGS}
  URL_HASH SHA256=${OPENJTALK_ARCHIVE_SHA256}
  CMAKE_ARGS ${OPENJTALK_CMAKE_ARGS}
  BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --config ${EXTERNAL_BUILD_TYPE}
  INSTALL_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --target install --config ${EXTERNAL_BUILD_TYPE}
  PATCH_COMMAND ${CMAKE_COMMAND}
    -DSOURCE_DIR=<SOURCE_DIR>
    -DCMAKE_SOURCE=${CMAKE_CURRENT_SOURCE_DIR}/cmake/OpenJTalk_CMakeLists.txt
    -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/patch_openjtalk.cmake
  BUILD_BYPRODUCTS
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}openjtalk${CMAKE_STATIC_LIBRARY_SUFFIX}
    ${OPENJTALK_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}mecab${CMAKE_STATIC_LIBRARY_SUFFIX}
)

add_dependencies(openjtalk_external hts_engine_external)
